spec:
  template:
    spec:
      containers:
      - env:
        - name: SERVICE_BINDING_DATABASE_DBNAME
          value: "..."
        - name: SERVICE_BINDING_DATABASE_DBCONNECTIONIP
          value: "..."
        - name: SERVICE_BINDING_DATABASE_DBCONNECTIONPORT
          value: "..."
        - name: SERVICE_BINDING_DATABASE_SECRET_USER
          valueFrom:
            secretKeyRef:
              name: "..."
              key: user
        - name: SERVICE_BINDING_DATABASE_SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "..."
              key: password
        readinessProbe:
          httpGet:
            path: /api/health/readiness
            port: 8080
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 8080
            scheme: HTTP
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
