spec:
  template:
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: "" # binding need to inject this
        - name: MY_DATABASE_SERVICE_HOST
          value: "" # binding need to inject this
        - name: DB_USERNAME
          valueFrom:
             secretKeyRef:
               name: "" # binding need to inject this
               key: user
        - name: DB_PASSWORD  
          valueFrom:
             secretKeyRef:
               name: "" # binding need to inject this
               key: password
        readinessProbe:
          httpGet:
            path: /api/health/readiness
            port: 8080
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 8080
            scheme: HTTP
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
