apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
spec:
  applicationSelector:
    matchLabels:
      connects-to: postgres
      environment: demo
    group: apps.openshift.io
    version: v1
    resource: deploymentconfigs
  backingServiceSelector:
    group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    resourceRef: db-demo
  mountPathPrefix: “”
  envVar:
    - name: JDBC_CONNECTION_STRING
      value: '{{ .spec.imageName }}@{{ .spec.image }}_{{ index .status.dbConfigMap "db.username" }}'
